---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: homeassistant
  namespace: traefik
  annotations:
    external-dns.alpha.kubernetes.io/hostname: home.jax-lab.dev
    external-dns.alpha.kubernetes.io/target: 192.168.8.50
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`home.jax-lab.dev`)
      kind: Rule
      services:
        - name: homeassistant
          port: 8123
  tls:
    certResolver: letsencrypt
