apiVersion: v1
kind: Secret
metadata:
    name: twingate-connector
    namespace: twingate
type: Opaque
stringData:
    TWINGATE_ACCESS_TOKEN: ENC[AES256_GCM,data:aGds7pf5BqkI9Il4t0pnFdNoeN/eIDbgqqPvF0N6VDcJVz97CQT+Zno//mDCvzFdJiWauUwSP5ni4Otbs7ak1dx+j491Fd98RwNHQJ1K7LethdZHU/veFj/s/drX65+oGMq6aFFkwOBqSDvTc2/WIaaX5uBvEiYhbTE+Jjr5GP8yjvBKIgO0uutoTSbAljSA1FqYW17cD4luGBSHFVkjkDfZ5uKD/D9n5SKn5VznAcckUfC+Xw4rPBnb80aw645Z0Y5Z8zFWpcsR2nvzxE2VO1u5jQFGDFX6msR4+iSErGb60R5lZAebLAM9t4Q0+777AriqrFYA+uTUHeTe94/gHzQ9++Ylf0mSy4T9b9xO2q/jP4DqgIEXfw9+HM0csRHeHi+OeyqBCk+w42crR59dxNTQ0ZaY55LRS9oJkkS38VW+r9G6DvjHpO560j+Vfhkmk9TmSa/DSTyMc0Yfgh99utW+y/aLnllwWch8U8ln0t+7bGYh1lPbfvQiLqvV61m4N1TimHg7akoguoC4v/bny7nS3XEWku8QqxzDu4QRrBs9/hiKKc/irnDZwS4wAwoEnzEvSaxFGaBtDi2SlKCFR4PybSvgYj2j6NR0apBeiPP4EBJk7OHqv0N7ZYF9MsRWkYHB4U7xT63cs4Vmagw=,iv:rbzmi4kGIeOdE3t8J6E9Kl8sfVx3I5Ep3gLE96SE+DQ=,tag:C2bLdYxeY0X8W/0+bXQGJg==,type:str]
    TWINGATE_REFRESH_TOKEN: ENC[AES256_GCM,data:IHwA+Sdy+d+a6SLS+tE5SRY57J3RfvI7WW/9SLBOBwtAY9UbsabzYx6uolmBoX4JGs3pIdaVueplOUHWQAXd/pyUgTxatyxZNnHLZ0eM6uVhR50xQsz2ArlIGIDcwIUQjy/QJTaJ1nosYJuguyDkc0drChIsrpwx6+UPMaEHOhE/RmFaqRs=,iv:vrxHOESpD9arpJ/VReFqat+rRwW7YdOBN7mI3TLVJXI=,tag:Dlq0kEhIa4MtHwAteB04nQ==,type:str]
sops:
    age:
        - recipient: age1hhwgd0zzsuqrg7gad42kh547lkgfeqsu03uql375uzslz0vqc37sknuux0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2a0VlMnVpenpKbURBM09l
            blpJOGhVc1htNG1pUXlPMWhuNHRnVHlIdkhJCkc1N29xMys2Q3VIa1BqeWU1czY5
            Z2RmRE5oYzU5d05DTU10cjVKSDJLOVUKLS0tIDVqZ21McUpsd1J5bGxGQUp6cUhS
            dlFxeXdqV3RxdC9PM3hTcXdJR1Z4STgK1Ex0h3FuBqPwaNcxWJpweYgWLxWVFlau
            Y9lw8utN7yPhzwOmWb8hznmu0gIrcCSajwOZfrxNYsxOcXHGibNJ2Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-02T20:58:30Z"
    mac: ENC[AES256_GCM,data:DqvHL8xJ3SFCrJd3gULfyDjd4xyjQMFt5J7k+bWlnYQcCSNKy/BiO7/1URXWg7Cib9Ft1+5Jor8OJIzfeeKucR1OWTGPPDAPIg8Rjczv66STRJK2vdQCdsk5jrs9HFMhDU98XJAq5dDx1aZtBilO+sXEDgvZ7ltGsEvN5xwzs9g=,iv:4nOmBUMoLI2ulhD4iNouqtIQIEBn2bjWYAJfaz5oWUA=,tag:gsXuMmiuSTMqYzz9RftR/w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
