apiVersion: v1
kind: Secret
metadata:
    name: twingate-connector
    namespace: twingate
type: Opaque
stringData:
    TWINGATE_ACCESS_TOKEN: ENC[AES256_GCM,data:bkDDBPyupDchpfuwdeXuukqCxQrtm9vHKBD27+gDZzgVZ3vKhHqOUTpaGqsLds4cqpJwMW/q76DdWLaRVeuYl3c6pLM8ipDYGj1L8wnrr4PNDJ5qJg7xPou87nccTYlXiCm2jMIjOgmCaEWo/r4HxIwHDg4rXerjwAyKP1jcdqV12ZXeKf2nP+WCf7HDt6MAwEl4qd+knRP+g4tcShtuW08n0Z8n1n9k213yWm4EhW+wUCuA81NcwWIgNXEEmazN0l9RZQx8G1KaEDpbzvONoGn7jpvE7EHjuAwDRnTLm0DEyreQ/UvQbDNi0eScPGnIWms4vvFgQvcdIGzVAw/EZZBUwIK+tAmpZWftN/tcnIQ7rldWiQtgctjrp/hoDOnescHwiyH03GWqKovO8s9q/p1INT/+qYN4n6UgVsp6s57lQXSKE/cVvYlaYOcNZrvDzOKPZrmlXMuHDJe8OR/Na9gXNvDw49z0eqK/1MQ1lG5M4R9JMMvYhs7szhxDS/JLETtY9IjysFF4+A2ZVHAtect5rTrw68DKnUOEHgOl7G0JJMu1LOv89LLvIwmZFEVMJOvgdPJY1YHuBY8vcylx/utzzLO8PjtRC3OcNcv7f1dSY5xwfpz1bBeIm/XJBnarrzYNBB4+44UQUnZRaRg=,iv:CUqxYwQAl+1IQ+K/aiQSdIq8ckTiNiaJ1utzQ0Q6urY=,tag:F8QQDwnoX3o1PwrN7TsCjQ==,type:str]
    TWINGATE_REFRESH_TOKEN: ENC[AES256_GCM,data:Z4Ueh6VjGMNcFh5X5qjqtu2njaPLjzMy2mDC5cwd+5raipnBO11SeKbZ8JVBHtMqhFP/nofDxfkSIDXygzsH9rT96/rOerUIEf1QTsqpGEBrlT5038N8bFXTJpYnj8yctFTFUKN1iaNQQNizGYoygho3xaPYCpcTNiZ7enmz53Xp73oJXb4=,iv:ORvzBB+SSwZiYdm5lTyQNvLAWIdpDwUZ45XyCKrfTDs=,tag:cYb7TN6H/dzyX/16wznESg==,type:str]
sops:
    age:
        - recipient: age1hhwgd0zzsuqrg7gad42kh547lkgfeqsu03uql375uzslz0vqc37sknuux0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3MWM2bkxwSC9tTGNodFZ6
            YmNhQ2FuQVJwVitYOTIrK1Bxa1VNTzdRWG40CjZVRk9LYi9kMFpoZDVlRVV0bUV3
            TC95eWZQRjhqb1ViU2lrL0lYRTdWeE0KLS0tIDZwcENCb1NBUEhib1UzancyWjB3
            QWFIRlhiV241Y2JSZzJjMU1rN01nU0kKrwQAnGlro5kdPWgcKBkDm0NRIMbWBV4C
            dHAYZokozoZKul9iPiVuOFbMnHyQBxttmLwJ2ytTAyZRAEJwu5ZISg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-02T00:49:27Z"
    mac: ENC[AES256_GCM,data:88U/6nSme7sWCARXLJcsBcK7h5eWcO8kfyeE5AZntiD44DQJhHJEl1rUrNUxhly1V7lgtKk8bQg1E2NCO4ZZjDXtszsJQfuM8h+K134w/Jmt3fQUo6Eolm/loZqlp6nddOihlydsI6ENYLwzPKKlV7AMi2UHcMizlETg/BWUQXA=,iv:KJJtPBM9vcQxJs6fRQswE9AEKo9lLINZNB+7B0EtiS8=,tag:nX1PYNEbvZnniXJF/3u5Ug==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
