# Loads default set of integrations. Do not remove.
default_config:

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 192.168.64.0/20     # IoT VLAN (local network)
    - 10.244.0.0/16       # Kubernetes pod network (Traefik)
    - 192.168.64.1        # N5 bridge64 gateway

openid:
  client_id: 37ba4af8-ae81-406f-9756-c90a15707993
  client_secret: tvRKAFRQhICR5JfOx7JJuy8MZQLHPxsz
  configure_url: "https://auth.jaxon.cloud/.well-known/openid-configuration"
  username_field: "preferred_username"
  scope: "openid profile email"
  block_login: false
  openid_text: "Pocket ID"

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# Timer helper for security lighting timeout
timer:
  security_lights_timer:
    duration: "00:05:00"
    name: "Security Lights Timer"
    icon: mdi:timer-outline

# GitOps test - Mon Nov 17 23:23:10 PST 2025

# Light groups for Inovelli switch automations
light:
  - platform: group
    name: Main Bathroom Vanity
    entities:
      - light.hue_color_downlight_5_3   # Bathroom South
      - light.hue_color_downlight_8     # Shower South
      - light.hue_color_downlight_6     # Shower North
      - light.hue_color_downlight_7     # Bathroom Center
      - light.hue_color_downlight_5_2   # Bathroom North
  - platform: group
    name: Main Bathroom Perifo
    entities:
      - light.perifo_cylinder_spot_1
      - light.perifo_cylinder_spot_2
      - light.perifo_cylinder_spot_3
  - platform: group
    name: Main Closet
    entities:
      - light.hue_color_downlight_1_2   # Closet 1
      - light.hue_color_downlight_5_5   # Main Closet 2
  - platform: group
    name: Main Bedroom Lights
    entities:
      - light.hue_color_downlight_4_2   # Hue color downlight 4
      - light.hue_color_downlight_3_2   # Hue color downlight 2
      - light.hue_color_downlight_1_4   # Hue color downlight 1
      - light.hue_color_downlight_2_2   # Hue color downlight 3
  - platform: group
    name: Dymera Lights
    entities:
      - light.dymera_1
      - light.dymera_1_2
      - light.dymera_2
      - light.dymera_2_2
