apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: vikunja-https
  namespace: vikunja
  annotations:
    external-dns.alpha.kubernetes.io/hostname: tasks.jaxon.cloud
    external-dns.alpha.kubernetes.io/target: 192.168.8.50
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`tasks.jaxon.cloud`)
      kind: Rule
      services:
        - name: vikunja
          port: 80
  tls:
    certResolver: letsencrypt
    domains:
      - main: tasks.jaxon.cloud
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: vikunja-http
  namespace: vikunja
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`tasks.jaxon.cloud`)
      kind: Rule
      services:
        - name: vikunja
          port: 80
