apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vikunja-data
  namespace: vikunja
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: openebs-zfs-homelab
  resources:
    requests:
      storage: 5Gi
