apiVersion: v1
kind: Secret
metadata:
    name: vikunja-secret
    namespace: vikunja
type: Opaque
stringData:
    #ENC[AES256_GCM,data:0uQkxSjaO4IxgF6EAHDSY+3BLM2a56oHGfvBp7Ncq7EfEgfgQIVi,iv:wOoP8m9Wqsl3Kazt6AiNpc3u3zM7vSFEqckGeAExLmE=,tag:+aahv6ThS5sKZrsg+rmYcA==,type:comment]
    JWT_SECRET: ENC[AES256_GCM,data:Vlr4xfzohCqUQvoT0NiB5pE4WJ5umudnNxc9d2JP6HFRJ6k07Q1U9y/B+C0=,iv:r8W51U2Fqz8k393+egOe56nNu+ZKucQwRJnxHjSViRQ=,tag:xQDuD6gj+NVdhdVl92UfPg==,type:str]
sops:
    age:
        - recipient: age1hhwgd0zzsuqrg7gad42kh547lkgfeqsu03uql375uzslz0vqc37sknuux0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5QmxnZlVGVnlRVjBWU2lJ
            THVlMzZkeGxRSXdUS0Z2Q21zV1JEeHNrcVFnCmw4em83amg2VXRDNDI3TkNIQmlD
            cW95N2U2ZlBoTkUzSXp3ay9SV0hkTEUKLS0tIDc1a0MxbVMyMHBLL0FaTnBSYXcw
            bUFDM0pSMDlWbjgrdGZQL0ZmYkZOMmsKHuERCnfJkwzOrBUmQJ5K+Zjx5ZhmzokU
            7tyCxu9RQhIaB42d6OwBhIVr6RPYn8/nGIxk+61HsTKOzNLUkMe3JA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-18T23:15:05Z"
    mac: ENC[AES256_GCM,data:XtjdrXQnFRftraUUrdJ7zwZe4TT8D1MmptUvfdWZ2+EaSNiXl3XeCSlDjltOxYUJp1sQWQEGwpZ6yuosXX9IPRC2lqMKE0vlhqNRVpiuYSqsckalbP055MucdUGed5BjnXINn/zWzwo/FrbEeY4AAdYO9q/NsxzOtWsfh2Jwwm4=,iv:VY/dLoz3/VlCSTqxSjlS2kPYuain1wxuNmlCbe6PpHg=,tag:eJtnZG+V6QKOqGpSy4/zEg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
