apiVersion: v1
kind: Secret
metadata:
    name: adguard-credentials
    namespace: external-dns
type: Opaque
stringData:
    ADGUARD_HOME_USER: ENC[AES256_GCM,data:TZFs,iv:/0i7LaO4dffcxtsDOu5yBTK4ez4+o3g1hVt8XSqBEBo=,tag:EFpZbQ1uY08J8eBn6Z9btg==,type:str]
    ADGUARD_HOME_PASS: ENC[AES256_GCM,data:DvLdnmQD8DQpvqTHWxhqxsKsXxY=,iv:Czsx66RWKBkwFtA3KdRNgVcf0zXsjdX/2UO+9fyAGLo=,tag:F4Q99tdKfKU6OGmOQMHcKQ==,type:str]
sops:
    age:
        - recipient: age1hhwgd0zzsuqrg7gad42kh547lkgfeqsu03uql375uzslz0vqc37sknuux0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOZHlHT0E5WUJKMEFQbXYx
            cDNsOWs3cWtzSEhGTmlGZjQ5SWo1WE5yNGhNCmR2c0tGNTBRbUpHTnZXOU1XWXUy
            WGpPdG1BY1dpc0JEVnNzMlBRcUNlbzQKLS0tIEx0UFFRaTZKb2RnWFVycEczZ1k3
            NDkzQ2Q4TnR2MDdaalV1dlNFeU1MQVEKs1miCmXbmeultIlzU0YbfTN78EsWRH17
            N9clCYvZqgZco2mWVVolEpDtd33/kxy1VG2LV1XvIudLhOKZeFBO/w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-01T23:32:30Z"
    mac: ENC[AES256_GCM,data:D+9ndhR/0CP5qsZnalq+quDqVVaTdgHstHqqIrA34BGY2jeHh1OjmCoaGd9gIx5/Pkk438mkbvtsP1Ez76K6LzDpi0Ffo86IQ7mAjq5Hi9ZKJKorwQLpSdX6VUfCyKi78v11MwUJ17FJS/RGOg19SmpLWrZDrkb9U0TKNe5iA30=,iv:RLCKJCqrwGM/3hB84oLvis+D/zFOU0wO6AufLwlHcbw=,tag:358k+CuMkGNoA10E0KUrNQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
