---
# VPS Public IP Pool for PHX cluster LoadBalancer services
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: vps-public-pool
  namespace: metallb-system
spec:
  addresses:
  - 85.31.234.30/32  # PHX VPS public IP (phx.jaxon.cloud / cloud.jax-lab.dev)
---
# L2 Advertisement for VPS public IP
# Announces LoadBalancer IPs via ARP on the VPS network
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: vps-public-advertisement
  namespace: metallb-system
spec:
  ipAddressPools:
  - vps-public-pool
