---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: homeassistant-lab
  namespace: homeassistant-proxy
  annotations:
    external-dns.alpha.kubernetes.io/hostname: home.jaxon.cloud
    external-dns.alpha.kubernetes.io/target: 85.31.234.30
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`home.jaxon.cloud`)
      kind: Rule
      services:
        - name: homeassistant-lab
          port: 443
          serversTransport: lab-transport
  tls:
    certResolver: letsencrypt
