---
apiVersion: v1
kind: Service
metadata:
  name: homeassistant-lab
  namespace: homeassistant-proxy
spec:
  type: ExternalName
  externalName: 192.168.8.50
  ports:
    - name: https
      port: 443
      protocol: TCP
      targetPort: 443
