all:
  children:
    homelab:
      hosts:
        n5:
          ansible_host: 192.168.4.5
          ansible_user: jax
          ansible_become: true
          ansible_python_interpreter: /usr/bin/python3
        m1-ubuntu:
          ansible_host: 192.168.4.81
          ansible_user: jax
          ansible_become: true
    cloud:
      hosts:
        phx:
          ansible_host: 85.31.234.30
          ansible_user: root
