apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: external-dns
type: Opaque
stringData:
    CF_API_TOKEN: ENC[AES256_GCM,data:3FkMIQNIgfXuZb3cSca4a0gBbqn3RaKaaTFRMhlSXgEuT85DMsfn/Q==,iv:sUKgwE5mETKET1K9btQLSaegy3rQuiK1GGEhiJNxeoo=,tag:I1qhYNZsO92grMQ/FmXGDg==,type:str]
sops:
    age:
        - recipient: age1hhwgd0zzsuqrg7gad42kh547lkgfeqsu03uql375uzslz0vqc37sknuux0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2U0s5WFJnRmJCTVFyYlRu
            L2o3TWwzMUluajZMZVpNM0cyMm1BM09EeWdvCkZ1ckFqVk8rWVEyK3JySGRoam1o
            d0JZaElYOHV0aTdNQzBRb0xJd1ErTTQKLS0tIDFMNkYyRkJIYXBSeFNNeTdVSVd1
            MHVGUzlwUU9TTU9oYmEwN1dKZzBnNk0K2KcDdtqPkcrNFGy+ztOEIUWOWqtRoP/c
            EbVcoDbdASzD5cx3e+TfaAhpwuCwGTH1Hu0pFeNHXB14uXgoVFcy1A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-02T19:31:53Z"
    mac: ENC[AES256_GCM,data:zuIMBGuyz+0baAJjiV8+qBT+DtCz83QB2Jdj/4jL0+rAg7lXqZq+LRp2cpglyAECWTQFr2upm+c2l24mPTGcxndftSAmmw1YEIL02kmjHtpHhI/Svk5Xnm6tX4HBzaLRUmD7YRdsATREqyORheKArP9q/G6yIPBNAFqjcLXVBrg=,iv:0lA/AwK5vFs8tm9ac66j/K9YKH/ySoap1MUuES1g1tk=,tag:jFL8jADznWaC3WrSyyEDmQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
