---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: pocket-id-https
  namespace: pocket-id
  annotations:
    external-dns.alpha.kubernetes.io/hostname: auth.jax-lab.dev
    external-dns.alpha.kubernetes.io/target: 192.168.8.50
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`auth.jax-lab.dev`)
      kind: Rule
      services:
        - name: pocket-id
          port: 80
  tls:
    certResolver: letsencrypt
    domains:
      - main: auth.jax-lab.dev
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: pocket-id-http
  namespace: pocket-id
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`auth.jax-lab.dev`)
      kind: Rule
      services:
        - name: pocket-id
          port: 80
