apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: traefik
type: Opaque
stringData:
    CF_API_TOKEN: ENC[AES256_GCM,data:96Jlv+GWw+InP3w3pRLbmBsYdmQ7O2bQJTK3JrBA3ZD5v884SQF66g==,iv:5RSgJaX1sUx7FTOOleexYOsPCTNzZUgOtqbXmOJNC3U=,tag:ejU+iu8JR8k8itvQsNkV0g==,type:str]
sops:
    age:
        - recipient: age1hhwgd0zzsuqrg7gad42kh547lkgfeqsu03uql375uzslz0vqc37sknuux0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwc29LdWVhckpLVjUwWFBX
            ZzN6dVhpbmdIaTBETksxK3NnTzdHNkVZOEM4ClhhdGFQMjJDMzBQSk1yb1g0K0dW
            eElRZ2h1M0Vyc2E0MzRNdTIvWEFQYmcKLS0tIFNUSTJCZ2tzdkkxdVZMNmNvc0VL
            dU90ZElHR1I4Q3F2U3JmRXhKeWwraWMKP+cxqGTbL60LknvyO09lKi/KWg3nVDYi
            vvCukzTexrNRsyiuRYaZW/6FPQFcU69dibCUnwuqBN3sHb9VXJZdWg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-19T04:29:16Z"
    mac: ENC[AES256_GCM,data:5xUi3e2nLRt8XGZehQOfJpZ/PwNA9srFL7t2TVIN3XJzOPbrB3WvAVAs9bi+/GfyAW4BV1jSor+/jyMgzRp3tvYltIYZlhdQfVWRTbe4/Pz1hgWisgyihEYh9oXWQdmK5Vl662m0zuDDCiuO3iTYVacEplvhtF0JYK2xrVSGurM=,iv:hdy+mboj7jV6IUZgjs/C64rgQQ+fp8tvPhdyiPcM+2k=,tag:Kdph4gZH5BV7xigw3UPuwA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
