---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - storage-classes.yaml
  - metallb.yaml
  - traefik-namespace.yaml
  - traefik.yaml
  - traefik-cloudflare.secret.yaml
