apiVersion: v1
kind: Secret
metadata:
    name: open-webui-oauth
    namespace: open-webui
type: Opaque
stringData:
    OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:DhMHpx/3nt+eNkzRIqVJ7tiFMUNTK5B1+K7nY7T35ZY=,iv:WQ8ayWVwNxxiAbHtMx6mWWKn3zOvhGDUI88jhku4ssg=,tag:++/kVQ/ym64mCmfQezyhCA==,type:str]
sops:
    age:
        - recipient: age1hhwgd0zzsuqrg7gad42kh547lkgfeqsu03uql375uzslz0vqc37sknuux0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLeGx3UmcxUERXUXFzMGJj
            RXZXMEo4NERKelFpREdyeksrZG50ZFpSZHhnCkU3TmR3WFdQRVBxYmtNblQwUE9D
            cldDTCtLRytCb05JR1lOaWdhdkQrazQKLS0tIHJLTEVpcjM0ZHpvMGloMk11STI0
            U1hmck8rT0lRd2x6dFZkbWV1ZU56YjgKjl30YQU8PMHtyIfR4VvWsSX+mLoHGei3
            7PxuqiGQuw/YnDsmkU1p9EUhnoJA+4lbPTF3d6xkuackRMHe2wRzFg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-02T23:15:51Z"
    mac: ENC[AES256_GCM,data:xcxy50ilHB4kOaM++taQi7XU+ubMAx5mitQItUy0JJUjtYABFRCl1ve8uqI9CzcNQ8wiUj0dA4CdHzzcKHYcZdn0Zu0PT593jxzIUK35scC2AEQX1qEqNjtuYQExPjzL5EYpUzWYyhRSl02cR8RxY788/SMM135hAjceF21d1/c=,iv:YamL5OM0+9T4b+NtRBNiv2uIRHeTUFvddux3RreAJpE=,tag:Ag5p8DZ/sn6CCSvuTTFveA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
