apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: homeassistant-deploy
  namespace: flux-system
spec:
  providerRef:
    name: homeassistant-webhook
  eventSeverity: info
  eventSources:
    - kind: GitRepository
      name: homeassistant
      namespace: flux-system
  eventMetadata:
    summary: "Home Assistant config updated"
