apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: homeassistant
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: homeassistant
  secretRef:
    name: flux-system
  url: ssh://git@github.com/ketterma/mobius
