apiVersion: v1
kind: Secret
metadata:
    name: adguard-oidc-config
    namespace: traefik
type: Opaque
stringData:
    #ENC[AES256_GCM,data:AapkEDm1LXEU53+CrhclwA7ijjBbvRay6+sP9syBcNeY,iv:e4BDxfZ7sBWLyf1QdIcwtzMFLcSKYl0lRTKKBGdDKa8=,tag:qiiVJXQ6la95NvJaRbUqIw==,type:comment]
    client-id: ENC[AES256_GCM,data:sHR5eLmeRlaNuVgZqckQJkhQBlsXlGIOGHgkiHCEKkSuHP3p,iv:p3B6sQbDUic9ywsd4t39Ydbw581XYOROGZEitzMlfs4=,tag:/mA+LdRmjst/7GyW/6l3zA==,type:str]
    client-secret: ENC[AES256_GCM,data:L1zzEtXxmyM06zo7AqgZgUVluVb6A+bsMNrnV3YsuPk=,iv:pnkRJzhNMi2KrqLVi7DqWnz0u+XEwx3nHTVHQDMYMX4=,tag:tJ852SvVDyOkJlamd6L7zQ==,type:str]
    #ENC[AES256_GCM,data:Wg6TKBlv+RJxp1fr3azKRP6UxBv98w7CwYV9WAGkP8RtsS8bj1badrQIyf+17kpFDw==,iv:JPQnoB/G8eTZ5FVtMjD2GS9S/hGbDcf63pLd88rS0nw=,tag:bS3sInpRqvbgwwQNXV1RBw==,type:comment]
    session-key: ENC[AES256_GCM,data:OXCxFW3raTZt7wC7QPDveFhigYEl5jVyAqPICSZMkJsAOZuVZYL6v2OWUAI=,iv:0oeGyLMx13QWS5hxTyNC46bkgJlGlFM1L3hsqxh6IxA=,tag:bb7DG4+Yhzb6ia/zKSg5yQ==,type:str]
sops:
    age:
        - recipient: age1hhwgd0zzsuqrg7gad42kh547lkgfeqsu03uql375uzslz0vqc37sknuux0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmeHI2Ukk5ZjFjb2V3RFFz
            WXhZY2R1M2EzaXdyQ0lXZ3pRbUJGb3IzWVhZCitwSlRTM3hBd3k1VjZkdXl0VjYx
            YWdzSTZSeVRGTFBJaTNnbGsrN25mbVUKLS0tIDFsWEpTNjZCdXZpUW5yMyt2bXFz
            cXpYU0JvSEdhckZHeEhGbjZVWnhCb0UKjaGqKxkodFYsf7t8+20QkZmIhsf+SZ+O
            h7Nj3+QjK6wt5GuQ6HWVuj4oc5E/9jdTpVKDhJz0Fvjd9LO0JLUF9g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-08T07:45:14Z"
    mac: ENC[AES256_GCM,data:/J9kWNOfnuSzDA5jNB2JArpFvU1Xb6BgvfGwsbIisIczVcUkkrdaSWuWba6YyQdIUd1g4s4jNuiHsoVe4093CkQ3ZhLXUm0n2dgzS3+F/3XOmROrUYtDU+EyfntU1MekxHEdKYMCOcKjVjolgMOcnKaLgiS2KKnEUDVktYy5iEY=,iv:4ExOESLTeV67ES9c9asWWSrAQSD19Dy5MQkQRXcSGNE=,tag:w//i3LYGLIf1TcrwlacqkQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
