apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: traefik
type: Opaque
stringData:
    CF_DNS_API_TOKEN: ENC[AES256_GCM,data:hqSrW2PAsKmQUGmOMeyiHEACQVNlixDi2XOUylhE2puqWgvWUXpPDQ==,iv:qiEUoJBbdtlnCmQ5sLIrIBBzHVegESa+qm5qnwdvUeU=,tag:/Mbj/4wFy5iM7D2jtJa9sw==,type:str]
sops:
    age:
        - recipient: age1hhwgd0zzsuqrg7gad42kh547lkgfeqsu03uql375uzslz0vqc37sknuux0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1RTBhRmk1SGFzbFNBdXJp
            dGJlTmNRLzg1SkNQTE5Ecmp6eVZKZnk2MEZzCmJRa1Q0Mys4YzNqdGZGbXFySkVL
            TWRXWkRiZXE2R05DN2hzQ3AxNEhJNkkKLS0tIHUyMk1IODBCbVhLbTB6R0tJZ3FN
            SXlPUVBmZWVoVkIzKzBvSHo0SzRBU1kKA9KHOzB5E/oqXFJRc2EInfuhbv2/Y8wl
            HqtPvL6XFdriyi5EG7m2dBoEtej1kFMy71RrmGe9BPCi//BItmv77w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-02T19:31:40Z"
    mac: ENC[AES256_GCM,data:MIjmgsS7nv/rzUIDxUG5+w7EdYdlX4UICHRZJ85RA3TMDhd60F7Uu1SbbCAGjlll0qcLv2QANuWlQB/NPyOYo8yA8owKue52CFliLJonWS6jJLZU2YaI4h4HZhw6ZkuqPUq4uDaaZRaBUlkMzN6S6Ix7NwqDtzdfiNhwhM/6FU8=,iv:aDlJRvVqQEKaCTJk3IIYoSA1hTAivNiYfVD6KDh/xoU=,tag:75NQCYTMpy01vMBwTPuhyQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
