apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: traefik
type: Opaque
stringData:
    CF_DNS_API_TOKEN: ENC[AES256_GCM,data:8CTUANt9fvMrcZBfwA0C4eeFMDFueLi0RQayf9OMyyTF3WJOj7OlNA==,iv:xkLkwJBeMKw0ZZbphOx4u6zK8Q96JvEVJLeB8skKaYs=,tag:iJDCxlHuVjvP+1Fr+1t8qQ==,type:str]
sops:
    age:
        - recipient: age1hhwgd0zzsuqrg7gad42kh547lkgfeqsu03uql375uzslz0vqc37sknuux0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmWWdZMEpzdXByQXVzZDZC
            RUZ3RmF6cDdGa0J1UDJlcXdRMTB5eUZSbHd3CkpUT3J4THdqL3lrRzgwdHFtM1dE
            SEhhQkJ1VVdFNk5XQTFjbTF3ZDVjZFEKLS0tIFRsdzBOK2ZmVytZMkk0YzlVNGNu
            Wk9XeUNWMUlscUxSNkltdnI1VmNBd1EKUrUMF8UEVVz2sEqkMb7fbWTCosiHqG7m
            hXNZ/LABpD6SvHeYrrhFALCv0wy7Ioxg0eEaX0bhdGbWM6SJdv7oJw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-02T21:34:04Z"
    mac: ENC[AES256_GCM,data:i3u5AP/068CnFtWczjuhyYeFxwNh3Tfm+ZXrpNfbQ1Xx7rsGjS7GBlCwbsnfCeMd6TM2dttHhqfHxMal2Gw2/0/JANHKSxq1HWfRe2LC9zNsjTlrxu8dl7mHLbRtvVdmAW7Glbp4aXoYmEKIxD0KCuSmdD60lYKMYxPvIxXRPcI=,iv:TN75xd1xlFxSBiqZr7963PvsgxO/e/agdbkAbO71A2I=,tag:QWwp3QXV688+6GzrC4FQWQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
