---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../base/infrastructure/metallb

patches:
  # Ensure MetalLB speaker only runs on N5 node
  - patch: |-
      apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      metadata:
        name: metallb
        namespace: flux-system
      spec:
        values:
          speaker:
            nodeSelector:
              kubernetes.io/hostname: n5
    target:
      kind: HelmRelease
      name: metallb
