apiVersion: v1
kind: Secret
metadata:
    name: twingate-client
    namespace: twingate-client
type: Opaque
stringData:
    service_key.json: ENC[AES256_GCM,data:0Twrh9SloHOvty7gXUkIA/NTYUNWKfY2ovyBeESwoVM9erYBa6lDx4CiPE0FsPaWHZfLrS0M09Kzfdtva/fvZkeU7hrzhtJ2gEJRbj9omzPW7/H+KonRilDzevOpA+fEqVUb+MxxNjBPXwdti67JR9rHrnlE7mg0hT5UHkxf+Fw64Sv+sXVho11s/MEswX54shQHUMHL+pTgiwklKGqRLm1sc2j8AKyvWCwejP1fiq64jXu+Rnp+xd2l+gKDz4Osx+80uk5NoyQbL0jqt4LPFigCP8HI02IAKAnsz5rahcEMQhZmLbUF7Vi7ne4fcASDaHGKy1OjEfitrOA99W2/ywyTR3FVnbEspQNpXBTSsqKPtGOKyPaI69otAXjHkjtuDDD64J67vqMsSrn1FDupGpcUdlKaLxH8FM8IQsb7VtFApYxX+J4D1aEhfdmneIDpoxzuqNM43hCE3mADjiMHZ1fwYX4J8uZe/BY/tHEZlconX26BBiVHLY/DPPECfjtNa5Rwpxa5srH421mCf8vd3hXmKfsIR0REzSbeFPifuPZOt3446fIfdtqb/cUzV4Q8mQWgopbsCtyfj1hLHJ7+Q61nW4gb7ttxx9byUDjKktfaUz+asSvmj3ckzZLq+Tk0rDlruGTEGNeRPnpEeKEuGKuGB3rv4w0TXs/hI3VaQWN0hg+DMIowoeWE+Q2NAiRPWit50A==,iv:oSNvmbznChyzHghU+T/qLB81UyE5czrfMuRBBvyv2kg=,tag:g43w9lnORiJOuqZezZGPXA==,type:str]
sops:
    age:
        - recipient: age1hhwgd0zzsuqrg7gad42kh547lkgfeqsu03uql375uzslz0vqc37sknuux0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkQjBHWGNMYTNqbFdxTjFH
            dUF6blFxU2VJc1hFcG40bXYyeFl5UEFRdlVZCnpCbVIvQy9ZNmZaTm1DdnJDUWpF
            Y1RFSU5QYmdkZWdkVEc4N00rUzcrdlEKLS0tIHJCSjdoeG5kZzdDbzBTU1prNWJO
            d01Ba1FTNFIyUlYzaCtjRXVmNm1ia3MKMgFmmBV1KPu5gwb9EgfqhOmWrZyGuwmc
            l+9t5JsYF+e29oR9YqHnvD4l/yXIUoFTI0+NIHHBnUvNFbyB/a4FMw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-08T08:28:07Z"
    mac: ENC[AES256_GCM,data:EKjxQ1egfzM0ZjVEKPOPkgb2u4M7BsAufjVAr7oOonqQfSSoCKtWnDR459vP/3JvS7lela6+SEbXXH1rjlFHosIPHMnDqvh+pDWW8zyzLdEWuzQS7nfMHlg8B1l7PVSeKMog1PhQgPARIGzb6rABU6y+hLvcMxtrXhVbhV7fn+E=,iv:ynEXTAgPoigceP77ZByJ+tzv0mb5L8pgILMTAQVd5g4=,tag:/ItglhdTIj+93mfdjDi+xg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
