---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adguard-conf
  namespace: adguard-home
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: openebs-zfs-homelab
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adguard-work
  namespace: adguard-home
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: openebs-zfs-homelab
  resources:
    requests:
      storage: 5Gi
