apiVersion: v1
kind: Secret
metadata:
    name: twingate-connector
    namespace: twingate
type: Opaque
stringData:
    TWINGATE_ACCESS_TOKEN: ENC[AES256_GCM,data:LuAlDn7pxcax16Ofx+0eFfMes0oJw/z4icUixdYJsmLiegqNj0NLkQ1MnSMLT2vg8dl5qjUMhrad7GRLhmNAfznWIYiEzokRu8dZP6XdZOfpSBZjrqzvBIVPvcSAHVSSI5J3QDifHOpxEBFZ9VryyOhRxtnmOlQUKj16RWaeaUq2c5UBKxahQc2qtoDlztRcYR0Fvv+p6Q6wOpBEolfbX1Ub33fPzDYlV/rgwN6K4ZwNHgodR9WqtopN6zKrxVJpyYnQ89VqMGw8sLNdCguPfDbeL8i8aP0d2kOVyfHNXEa3Fi6IrrdTMqe7JAM7HyW7smYD7ncx9zozshr75SOalPJSdz5bWUYJMY1qNbqckyBUc8mVUCb0AuM/fyLPQcB6iWto6Jj7Xzlz2gV04h62qU65G98UXwKkNMKpaIkwZgZfj9cI9m70y9nCMb0+YG9T/AYOCVaXMBhqXAhwaCxkIa+8jtwHBSiCvDwnZb8KVJ53Z4Zv639MEtEVgJTdwe9DUcBVTOkuVkIwcObLvp/rGR8d7cf1nT03ps+FNCyJRa2ejrz/I1rPswwm797FlwtNY5emGYWq1/DsbDTZeHTuFwD7E3W6Ormx0HFzk4FjC1Rrks+bwFm6m989S8f6OQq6psXlm1ksVCYVToi2FbM=,iv:4GqTHG6s5Kmgb+Dy7l7lmqGfgbXUrmR0ffdcVytsLho=,tag:c6wnbQ13hKwlhQ6TrVxzLA==,type:str]
    TWINGATE_REFRESH_TOKEN: ENC[AES256_GCM,data:uj15w5QatS9uxULrAFP9O2q2JDGPjpgwhORX5LbhqtrjX/Y1M6IEcv0iFjY9O0Q7MItnBdTCnVAF/KWZxdGLmn/ChRpeLg9nnpSJ0kq8F2h0dEog8Hb3NCy6gXrEVz3t2plzX7/+bq0tozpbgNjsWjkkfu9Vj8rgWCGGDs8OQUrQViNrqgs=,iv:/hHAE4pMeK6WgJJQmTpWk/HHBi2J1xCyBUOE66qeroM=,tag:rfrom/El+Zdqc5/vcRg6Vw==,type:str]
sops:
    age:
        - recipient: age1hhwgd0zzsuqrg7gad42kh547lkgfeqsu03uql375uzslz0vqc37sknuux0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnRDhTZVlhREJSYXg5K1c1
            MGZxR0V1TDNYSHhJRlVkY2Qzc0wvSzkxVVhVCkxZblBEak1UTGRKSHhmc2lvcFJZ
            c2VDTjVBS0pOWlNKdkQ4RGh1M2tRamMKLS0tIGVOTEdnanFDWDg4QkxtQldxRzBT
            ZUZ4M0pmTzkrTGRIMmZGYXAwZmtNNzgKcROHAdRJ6aeyKJqADioFmqLGoQYoCA1i
            2mN09PBwzwCDrKZ5TfOPdUJVAxkbAK2jbDSF012WcCgIvfimKVt7Pw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-02T22:30:29Z"
    mac: ENC[AES256_GCM,data:kgMFLRWS8Sq4+iNCDbMa1n0DWJMimSMIVa/BNog5i2pBYfhm9lMUB1UXhsOfKEbyblTGSFFkOOh7QfGLyh+q2bdnBmlX2rGzCi1ueBpJeTMuEvRMxinOnfatYe5/XJat0gvDSSM6XLlOid/JpDFD6Zmcn2aw6zg0Vy09GAsO5vc=,iv:e595npbJT9n+KQYhFJYd+D+XKQXNk+lSvWjU5t79HEo=,tag:+tDBzw5KPMkRqqf2beiqLw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
