apiVersion: v1
kind: Secret
metadata:
  name: twingate-connector
  namespace: twingate
type: Opaque
stringData:
  TWINGATE_ACCESS_TOKEN: "PLACEHOLDER_GENERATE_PHX_CONNECTOR_IN_TWINGATE_DASHBOARD"
  TWINGATE_REFRESH_TOKEN: "PLACEHOLDER_GENERATE_PHX_CONNECTOR_IN_TWINGATE_DASHBOARD"
