apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nexterm-data
  namespace: nexterm
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: openebs-zfs-homelab
  resources:
    requests:
      storage: 5Gi
