---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: supabase
  namespace: supabase
spec:
  interval: 1h
  url: https://github.com/supabase-community/supabase-kubernetes
  ref:
    branch: main
