---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: supabase
  namespace: supabase
spec:
  interval: 30m
  chart:
    spec:
      chart: supabase
      version: '>=0.1.0'
      sourceRef:
        kind: HelmRepository
        name: supabase
        namespace: supabase
      interval: 12h
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: supabase-values
      valuesKey: values.yaml
  dependsOn:
    - name: metallb
      namespace: metallb-system
