apiVersion: v1
kind: Secret
metadata:
    name: supabase-secrets
    namespace: supabase
type: Opaque
stringData:
    #ENC[AES256_GCM,data:r5GcHUvX3Yxrro4i6H4Jif6g,iv:nCiIde425/UATORxX+nNrBhZN9BqRFtRrrKY6OPznmI=,tag:GsSqKQHzfQWHe4pTpC+khA==,type:comment]
    jwt-secret: ENC[AES256_GCM,data:a8OXRocYqkesOmox8gyzYcEFszTPKGPpkJdrflwMCqzTn/d2p6B9jC+oFkk=,iv:Ngr+t1C7MUSDoZoIQYq5iQQqrHqWM+u6O/2qXRF2Wz8=,tag:9b0wfVnGf7gNDL3z5WPGIg==,type:str]
    anon-key: ENC[AES256_GCM,data:ZUAVBIjJEKcpAnk+D/ikiQUdIimg2d+dRtQcnHyPn35H3DAgtAHNhSxp+aS0P5orbZyg4WmtmS8/AS8aNdSbTnj9/qe2kWnqQSaAV9KY4ZXDwXJhUH2S+oTKcQhbgaUaJBstt1WxTbPbI1ovml2NhCBYO8QFY4xhStm8dS+p0lpIpiuZ8hTGF7ycCi6y6SBaul98D6etisB/7sTd/x+xyEBds2ego6GE8A==,iv:YMIZMT4KD8VrV6pxffDu9fLGyfn+pu+VRbeYOebPAJE=,tag:MCJI0LndglcujCo/MMVeyg==,type:str]
    service-key: ENC[AES256_GCM,data:GtxJtV8L1DihEOqJ5NcSpFoCiLB+WuSZcgxWj/4ihVwILAxn2DWSoy/XAFK3QMzOPj2vtLaNbUfgP+BSCRypcNoO4Xy9Yl0MmSygQWilz1pUIlYXJcStousHVdhhqec8IAYs2xQD81JKZFVPjvekGKi+hnmuliMEeO680zM0ffVoN+eDlhdb/GSbyd1aPE7aGRLR+n/aWbLt3LkadIH3RayVDi0q+i0hS8OZtrSvslZC6jyc,iv:o8gE6Yv3hl/6jCcG5MEDVrQ/h8P7PAcoRsCGO/Cbe30=,tag:YVvKfE+lgmJLrKYbE7Jk+A==,type:str]
    #ENC[AES256_GCM,data:ydBz7G9yXY35jL1dCm/bnHSfpJll,iv:oji1TBYAFwk6au7Pklz5/ygIu2LAwTIE0n22uwgMmJ8=,tag:6F3kYUaaH4UAA9odOaKQ+w==,type:comment]
    db-username: ENC[AES256_GCM,data:3vDYJStTv3g=,iv:R/0Q9qu39sqBwfcnl9VGkLg7Es7m2ZN/msM6WaDMMBQ=,tag:iST3sqeUANvYx5tIWPi4pA==,type:str]
    db-password: ENC[AES256_GCM,data:fY3KGa8Ov9nhGl0M7LgZM0M/fNCYwSMjl62pXF9Y+ng=,iv:yJUJIl7fF59bFGunraLrsj796q7LICGI5WkjWVEy0fc=,tag:+AW4La9BfFLgOkyKPHdd8g==,type:str]
    db-database: ENC[AES256_GCM,data:KRh3eJSyL1c=,iv:oOb8MPrnDp3PXAQoiO0iI7Lr0/opuakvgnWXWyBC6Us=,tag:3cP995YflUygNZNgkJbUaQ==,type:str]
    #ENC[AES256_GCM,data:QiNOLvb43ePkeAsEIKZ+RTpQxOG/aA==,iv:cQ97+Sm3fgf/gF3Lv1jGiy3YjsADBW7MCdGp7qqnQ+4=,tag:BBL3HGUVn+1osnJZdC1N+w==,type:comment]
    dashboard-username: ENC[AES256_GCM,data:zaX7KoEOfos=,iv:r8W1DF6nJoHCayo8vfuPy/EBYkiuDKV+vXipJpFZ704=,tag:vQwNro4pIa4T6iazGWfwig==,type:str]
    dashboard-password: ENC[AES256_GCM,data:IhuC5RrSQun3jnbllfTOZRA9Pnl1mThFph7CjVqI4cU=,iv:QpiO/1/U3IpQU6SvcBZRXk+v4AkuIBLWdNw4PVKNff8=,tag:NGL08fZjViWnvDqjXv3U6g==,type:str]
    #ENC[AES256_GCM,data:GwwVASPqWJ9BEQ==,iv:IT0LyqCHivWsMcaSS031Gn7EO6LCTk2DpaqqSOM9bBE=,tag:vRMuC7d4wBXGLD5iONuHgA==,type:comment]
    analytics-api-key: ENC[AES256_GCM,data:tjmFFTubESc+2U/hAhSWkxebkNB2eQhKUt40jHP6z/lBNwCotq8WYMpW1wA=,iv:XiaksHdwI7/+b5kQP5xQagsIYlxwuLffFMu8EFZxKok=,tag:ZzWzJWzfGn2QPodfvEE4Iw==,type:str]
sops:
    age:
        - recipient: age1hhwgd0zzsuqrg7gad42kh547lkgfeqsu03uql375uzslz0vqc37sknuux0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGMHA5U3czdWJhaVRZdGlE
            dlg4YkFpWjdZQlp2V1g1UU9jeTJ1Tk82QXhNCjAxRTNOQ2x6NTlMNEtqdXBGdXR0
            QkZLVGJ4UVJacmh4TzJLS3dJTjNRNTQKLS0tIElFZmVEUkF0QUhwR00ySUl4WURU
            SHF4cjhkTGhxekZCTmZhOEYxN0gwbjgKFk2IjXWuWjqVsn+3ilPM4/L71T4q9Pva
            MHFiAxSI5pGcQkF0nLd58T0fViF1a/KMJNclhjajVy8/zIz4Q1xDZw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-07T07:44:49Z"
    mac: ENC[AES256_GCM,data:HGyj5spDiv7EmP98qhS9pzUmHu9Rjytg3NR7yf4tW787vyQEOXGzYlyiAfC8Bi968y3azg27C/l+4Qql5Ytl1yBK1G0OUi+7Lg++cAoUXzYPgmyVg92rgz+pd+er4eeIqqF3cHr2XjyLabGXRlm8sGi8rKaA02l5clvc52Gy/Vk=,iv:mF+Q2/D8l3GAFMJKtNQZyYQTeiHmTOT68+lTrGBMRCM=,tag:B82WP311unVk1tDj9z97Rw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
